### ISSUE TITLE
use const

### ISSUE THREAD

**Issue by soggybag** [pomfy113/Reddit-Clone#9]
https://github.com/pomfy113/Reddit-Clone/blob/eee24de78e3cb28e1ee381fb5c14f522a3c1861a/models/user.js#L1

Use const here. 

Better as:

```
var mongoose = require('mongoose');
const bcrypt = require('bcrypt');
const Schema = mongoose.Schema;
```

**Comment by pomfy113** [comment]
Changed, but to
const mongoose = require('mongoose');
const bcrypt = require('bcrypt');
const Schema = mongoose.Schema;

Instead of
var mongoose = require('mongoose');
const bcrypt = require('bcrypt');
const Schema = mongoose.Schema;

If requires shouldn't be const, please advise.
